Overhead of using the OMOP
==========================

TODO: back to main


```{r init, echo=FALSE, message=FALSE, warning=FALSE, results='hide', errors=FALSE}
# load libraries, the data, and prepare it
if (Sys.getenv("RSTUDIO") == "1") { setwd("/Users/smarr/Projects/PostDoc/ZERO-MOP/perf-eval-selfopt/") }

options(scipen=5)

source("scripts/libraries.R", chdir=TRUE)
data <- load_data_file("data/zero-overhead.data")
data <- subset(data, select = c(Value, Unit, Benchmark, VM, Suite, Var, rid))
data <- prepare_vm_names(data)

## Add a time series id
data <- ddply(data, ~ Benchmark + VM + Var, transform,
              Iteration = rid - min(rid))

simple_boxplot <- function(data_set, vm, x = "Benchmark", y = "Value") {
  data_vm <- droplevels(subset(data_set, VM == vm))
  
  p <- ggplot(data_vm, aes_string(x=x, y=y))
  #p <- p + ggtitle(vm)
  p + geom_boxplot() + theme_simple()
}
```

Simple Behavioral Changes
-------------------------

To assess the overhead of using the OMOP instead of implementing the same
semantics on the base level, we constructed a few simple microbenchmarks.



```{r complete-overview, fig.width=12, fig.height=4, dev='svg'}
# Ignore Dispatch, DispatchEnforced and DispatchEnforcedStd are the proper benchmarks
omop <- droplevels(subset(data, Suite == "omop" & Benchmark != "Dispatch" & Iteration > 50))

omop <- ddply(omop, ~ Benchmark + VM + Suite, transform,
               Var = grepl("Enforced$", Benchmark),
               Benchmark = gsub("(Enforced)|(Std)", "", Benchmark))
omop$Benchmark <- factor(omop$Benchmark)

## Boxplot with all benchmarks, only the enforced version, normalized, and shown around 1.0 line
norm_omop <- ddply(omop, ~ Benchmark + VM + Suite, transform,
                   RuntimeRatio = Value / geometric.mean(Value[Var == FALSE]))
norm_omop_enforced <- droplevels(subset(norm_omop, Var == TRUE))

for (vm in levels(norm_omop_enforced$VM)) {
  p <- simple_boxplot(norm_omop_enforced, vm, y = "RuntimeRatio")
  p <- p + ggtitle(vm) + scale_y_continuous(name="Runtime Ratio to run without OMOP") + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5))
  print(p)
}
```
