---
title: "Stefan: Looking at MaxRSS for Test1-100 and TestGC1-100"
output: html_document
date: "2023-04-07"
---

```{r setup, include=FALSE, echo=FALSE}
source("../scripts/libraries.R", chdir=TRUE)
source("../scripts/data-processing2.R")

data <- qread("../../../../data/smarr-mem-use.qs")

med <- data |>
  group_by(bench, exe, inputsize, criterion, unit, exe.bench) |>
  summarise(median = median(value),
            .groups = "drop")
```

## MaxRSS Increase


```{r maxrss-increase}
ggplot(med, aes(x=inputsize, y=median, group=exe.bench, color=exe.bench)) + geom_line()
```

## Per Iteration Increase

```{r per-iter-increase}
med_diff <- med |>
  group_by(bench, exe, criterion, unit, exe.bench) |>
  mutate(diff = median - lag(median)) |>
  na.omit()
ggplot(med_diff, aes(x=inputsize, y=diff, group=exe.bench, color=exe.bench)) + geom_line()
```

## Stats

```{r stats}
stats <- med_diff |>
  group_by(bench, exe, criterion, unit, exe.bench) |>
  summarise(median.diff = median(diff),
            .groups = "drop") |>
  mutate(is.pysom = str_detect(exe, "PySOM"))

base <- stats |>
  filter(str_detect(exe, "BC")) |>
  mutate(base = median.diff) |>
  select(!c(exe.bench, median.diff, exe))

norm <- stats |>
  left_join(base, by = c("bench", "criterion", "unit", "is.pysom")) |>
  mutate(ratio = median.diff / base)

id <- function(x) { x }

tabular(bench*exe ~ (median.diff + ratio) * id, data=norm)
```
## Code Stats

```{r code-stats}
code_stats <- read.csv("../../../../data/program-rep.cloc.csv")
code_stats$language <- factor(code_stats$language)
tabular(
  language ~ (files + blank + comment + code) * id,
  data=code_stats)
```
