# Impact of individual optimisations

## AST

```{r load-scripts, echo=FALSE, include=FALSE}
# load libraries, the data, and prepare it
if (Sys.getenv("USER") == "smarr") {
  setwd("/Users/smarr/Projects/ast-vs-bc-interp/are-we-fast-yet/report/bc-vs-ast")
  } else if (Sys.getenv("USER") == "sopi") {
  setwd("/home/sopi/Documents/Writing/2023/ast-vs-bc-interp/are-we-fast-yet/report/bc-vs-ast/" )
  } else {
  setwd("/home/octavel/PhD/papers/ast-vs-bc-interp/are-we-fast-yet/report/bc-vs-ast")
  }
source("scripts/libraries.R", chdir=TRUE)
source("scripts/data-processing2.R")

OPTIM_GRAPH_HEIGHT <- 1.3
OPTIM_GRAPH_WIDTH <- 2.6
MIN_JIT_ITERATION <- 1000
MIN_JIT_ITERATION_FOR_OLD_DATA <- 50

compute_stats <- function(data, exe_name, iteration_threshold = 0, baseline_optim="all optimizations") {
  # compute_stats(data_optim_pysom_ast, "RPySOM-ast-interp")
  # data <- data_optim_pysom_ast
  # exe_name <- "RPySOM-ast-interp"
  
  # remove all the columns we don't need for this
  # and keep only the exe we are interested in
  data <- data |>
    select(!c(commitid, suite, cmdline, varvalue, cores, expid, runid, trialid, envid, inputsize, extraargs, warmup, invocation)) |>
    filter(exe == exe_name)
  
  # then selected the "warmed up data"
  jit_exe_vals <- c("RPySOM-bc-jit", "RPySOM-ast-jit", "TruffleSOM-graal", "TruffleSOM-graal-bc")
  if (exe_name %in% jit_exe_vals) {
    data <- data %>% 
      filter(iteration >= ifelse(max(iteration) == 2000, MIN_JIT_ITERATION, MIN_JIT_ITERATION_FOR_OLD_DATA))
  } else {
    data <- data %>% 
      filter(iteration >= iteration_threshold)    
  }
  
  # now, and only now, let's isolate the baseline, and pick the median
  base <- data |>
    filter(optim == baseline_optim) |>
    select(!c(optim)) |>
    group_by(bench) |>
    summarise(base_value = median(value))
  
  
  # and finally, we can normalize things
  norm <- data |>
    left_join(base, by = c("bench")) |>   # add the base_value column per join
    transform(ratio = value / base_value) # do the unit conversion
  
  # TODO: remove, this is needed because we have old benchmarks in there
  norm <- norm |>
    filter(!is.na(base_value))

  stats <- norm %>%
    group_by(optim, exe) %>%
    summarise(
      unit = unit[1],
      min = min(ratio),
      max = max(ratio),
      sd = sd(ratio),
      mean = mean(ratio),
      median = median(ratio),
      samples = length(ratio),
      .groups = "drop")

  list(
    base = base,
    norm = norm,
    stats = stats)
}

get_data_for_box_plot_optim <- function(input_data, exe_name, baseline_optim_name="all optimizations", iteration_threshold=0) {
  all <- compute_stats(input_data, exe_name, iteration_threshold)
  all$norm # %>% filter(!is.na(expid.y))
}

box_plot_optim <- function(data, custom_x_breaks=NULL, colors = color_set_optims) {
  if (is.null(custom_x_breaks))
    x_breaks <- c(0.5, 0.8, 1, 1.5, 2, 3, 5, 10, 15, 30, 50, 100, 300)
  else
    x_breaks <- custom_x_breaks

  plot <- ggplot(data, aes(x=ratio, y=reorder(factor(optim), -ratio, FUN = median)))
  plot <- plot + 
    geom_vline(aes(xintercept=1),    colour="#999999", linetype="solid") +
    geom_vline(aes(xintercept=1.5),  colour="#999999", linetype="dotted") +
    geom_vline(aes(xintercept=2), colour="#999999", linetype="dotted") #+
#    geom_vline(aes(xintercept=10), colour="#999999", linetype="dotted")
  plot <- plot + geom_boxplot(outlier.size = 0.7,
                              outlier.alpha = 0.6,
                              width=0.5,
                              outlier.shape = 22,
                              aes(colour = optim, fill = optim), 
                              alpha=0.5) +
    scale_x_log10(breaks = x_breaks) +
    scale_color_manual(values = colors) +
    scale_fill_manual(values = colors) +
    theme_simple() +
    theme(
      axis.text.x = element_text(angle= 90, vjust=0.5, hjust=1),
      axis.title.x  = theme_simple_axis_title(),
      legend.position="none") +
    #scale_y_log10(breaks=c(1,2,3,10,20,30,50,100,200,300,500,1000)) + #limit=c(0,30), breaks=seq(0,100,5), expand = c(0,0)
    ylab("") +
    xlab("normalized run time, lower is better")
  
  plot
}

box_plot_optim_unified <- function(data, custom_x_breaks=NULL) {
  if (is.null(custom_x_breaks))
    x_breaks <- c(0.5, 0.8, 1, 1.5, 2, 3, 5, 10, 15, 30, 50, 100, 300)
  else
    x_breaks <- custom_x_breaks
  
#  breaks <- levels(droplevels(data)$optim)
  #vm_colors <- rainbow(255)
  col_values <- rainbow(10)
  
  plot <- ggplot(data, aes(x=ratio, y=optim, fill = optim))
  plot <- plot + geom_boxplot(outlier.size = 0.5) +
    scale_x_log10(breaks = x_breaks) +
    scale_fill_viridis_d() +
    theme_simple() +
    theme(
      axis.text.x = element_text(angle= 90, vjust=0.5, hjust=1),
      axis.title.x = theme_simple_axis_title(),
      legend.position="none") +
    #scale_y_log10(breaks=c(1,2,3,10,20,30,50,100,200,300,500,1000)) + #limit=c(0,30), breaks=seq(0,100,5), expand = c(0,0)
    ylab("") +
    xlab("") + 
    geom_hline(yintercept = 8.5, linetype = "dotted")
  
  plot
}

load_data_for_experiment <- function(experiment_ref, optim_name, project_name) {
  load_data_url(paste0("https://rebench.stefan-marr.de/", project_name, "/data/", experiment_ref)) %>% mutate(optim = optim_name)
}

# (*) means AST/BC specific optim
get_tsom_ast_data_no2k <- function() {
  project_name <- "TruffleSOM"
  rbind(load_data_for_experiment(2762, "all optimizations", project_name),
        load_data_for_experiment(2759, "local/nonlocal vars", project_name),
        load_data_for_experiment(2753, "inline caching", project_name),
        load_data_for_experiment(2752, "global caching", project_name),
        load_data_for_experiment(2751, "lowered control struc.", project_name),
#        load_data_for_experiment(2625, "blocks without context", project_name),
        load_data_for_experiment(2761, "supernodes (*)", project_name),
        load_data_for_experiment(2816, "lowered basic ops", project_name) 
        ) %>% filter(criterion == "total")
}

get_pysom_ast_data_no2k <- function() {
  project_name <- "RPySOM"
  rbind(load_data_for_experiment(2780, "all optimizations", project_name),
        load_data_for_experiment(2771, "local/nonlocal vars", project_name),
        load_data_for_experiment(2764, "inline caching", project_name),
        load_data_for_experiment(2770, "global caching", project_name),
        load_data_for_experiment(2811, "lowered control struc.", project_name),
#        load_data_for_experiment(2658, "blocks without context", project_name),
        load_data_for_experiment(2812, "lowered basic ops", project_name)
        ) %>% filter(criterion == "total")
}

get_tsom_bc_data_no2k <- function() {
  project_name <- "TruffleSOM"
  rbind(load_data_for_experiment(2762, "all optimizations", project_name),
        load_data_for_experiment(2785, "inline caching", project_name), # -Test is disabled in that one, which is a tad dirty... results are bad, anyway, needs more work
        load_data_for_experiment(2759, "local/nonlocal vars", project_name),
        load_data_for_experiment(2756, "quickening (*)", project_name),
        load_data_for_experiment(2754, "global caching", project_name),
        load_data_for_experiment(2751, "lowered control struc.", project_name),
        load_data_for_experiment(2757, "superinstructions (*)", project_name),
        load_data_for_experiment(2816, "lowered basic ops", project_name)
        ) %>% filter(criterion == "total")
}

get_pysom_bc_data_no2k <- function() {
  project_name <- "RPySOM"
  rbind(load_data_for_experiment(2780, "all optimizations", project_name), 
        load_data_for_experiment(2764, "inline caching", project_name),
        load_data_for_experiment(2772, "global caching", project_name),
        load_data_for_experiment(2774, "quickening (*)", project_name),
        load_data_for_experiment(2775, "superinstructions (*)", project_name),
        load_data_for_experiment(2811, "lowered control struc.", project_name),
        load_data_for_experiment(2812, "lowered basic ops", project_name)
        ) %>% filter(criterion == "total")
}

get_tsom_ast_data <- function() {
  project_name <- "TruffleSOM"
  rbind(load_data_for_experiment(2848, "all optimizations", project_name),
        load_data_for_experiment(2862, "global caching", project_name),
#        load_data_for_experiment(2874, "local/nonlocal vars", project_name),
        load_data_for_experiment(2884, "inlined control struc.", project_name),
        load_data_for_experiment(2863, "lowered basic ops", project_name),
        load_data_for_experiment(2886, "inline caching", project_name),
        load_data_for_experiment(2875, "supernodes (*)", project_name)
        ) %>% filter(criterion == "total")
}

get_tsom_bc_data <- function() {
  project_name <- "TruffleSOM"
  rbind(load_data_for_experiment(2848, "all optimizations", project_name),
        load_data_for_experiment(2869, "superinstructions (*)", project_name),
        load_data_for_experiment(2868, "quickening (*)", project_name),
        load_data_for_experiment(2863, "lowered basic ops", project_name),
        load_data_for_experiment(2884, "inlined control struc.", project_name),
#        load_data_for_experiment(2874, "local/nonlocal vars", project_name),
        load_data_for_experiment(2861, "global caching", project_name),
        load_data_for_experiment(2785, "inline caching", project_name) # OLD DATA
        ) %>% filter(criterion == "total")
}

get_pysom_ast_data <- function() {
  project_name <- "RPySOM"
  rbind(load_data_for_experiment(2873, "all optimizations", project_name),
        load_data_for_experiment(2877, "global caching", project_name),
        load_data_for_experiment(2891, "inlined control struc.", project_name),
        load_data_for_experiment(2764, "inline caching", project_name), # OLD DATA        
        load_data_for_experiment(2891, "lowered basic ops", project_name)
        ) %>% filter(criterion == "total")
}

get_pysom_bc_data <- function() {
  project_name <- "RPySOM"
  rbind(load_data_for_experiment(2873, "all optimizations", project_name),
        load_data_for_experiment(2876, "global caching", project_name),
        load_data_for_experiment(2891, "inlined control struc.", project_name),
        load_data_for_experiment(2892, "superinstructions (*)", project_name),
        load_data_for_experiment(2764, "inline caching", project_name), # OLD DATA
        load_data_for_experiment(2894, "quickening (*)", project_name),
        load_data_for_experiment(2891, "lowered basic ops", project_name)
        ) %>% filter(criterion == "total")
}

data_optim_tsom_ast <- get_tsom_ast_data()
data_optim_tsom_bc <- get_tsom_bc_data()
data_optim_pysom_ast <- get_pysom_ast_data()
data_optim_pysom_bc <- get_pysom_bc_data()

all_optims <- rbind(data_optim_tsom_ast, data_optim_tsom_bc, data_optim_pysom_ast, data_optim_pysom_bc)
unique_optims <- unique(all_optims$optim)

color_set_opti <- c('#081d58', '#AADC32FF','#472D7BFF','#3B528BFF','#FDE725FF','#440154FF','#1d91c0','#238b45','#ec7014')
color_set_optims <- set_color_bindings_for_plots(unique_optims, color_set_opti)
```

### TruffleSOM - AST interp

```{r optim-tsom-ast-int, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot_optim(data_optim_tsom_ast, "TruffleSOM-native-interp-ast")

plot <- box_plot_optim(box_plot_data)
ggsave(plot, device= cairo_pdf, path=".", filename=output_folder_path("optim-tsom-ast-int.pdf"), dpi=300, height=OPTIM_GRAPH_HEIGHT, width=OPTIM_GRAPH_WIDTH, units="in", family="Arial")
plot
```

### PySOM - AST interp

```{r optim-pysom-ast-int, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot_optim(data_optim_pysom_ast, "RPySOM-ast-interp")

plot <- box_plot_optim(box_plot_data)
ggsave(plot, device= cairo_pdf, path=".", filename=output_folder_path("optim-pysom-ast-int.pdf"), dpi=300, height=OPTIM_GRAPH_HEIGHT, width=OPTIM_GRAPH_WIDTH, units="in", family="Arial")
plot
```

### TruffleSOM - AST JIT

```{r optim-tsom-ast-jit, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot_optim(data_optim_tsom_ast, "TruffleSOM-graal")

plot <- box_plot_optim(box_plot_data)
ggsave(plot, device= cairo_pdf, path=".", filename=output_folder_path("optim-tsom-ast-jit.pdf"), dpi=300, height=OPTIM_GRAPH_HEIGHT, width=OPTIM_GRAPH_WIDTH, units="in", family="Arial")
plot
```

### PySOM - AST JIT

```{r optim-pysom-ast-jit, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot_optim(data_optim_pysom_ast, "RPySOM-ast-jit")

plot <- box_plot_optim(box_plot_data)
ggsave(plot, device= cairo_pdf, path=".", filename=output_folder_path("optim-pysom-ast-jit.pdf"), dpi=300, height=OPTIM_GRAPH_HEIGHT, width=OPTIM_GRAPH_WIDTH, units="in", family="Arial")
plot
```

## BC

### TruffleSOM - BC interp

```{r optim-tsom-bc-interp, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot_optim(data_optim_tsom_bc, "TruffleSOM-native-interp-bc")

plot <- box_plot_optim(box_plot_data)
ggsave(plot, device= cairo_pdf, path=".", filename=output_folder_path("optim-tsom-bc-int.pdf"), dpi=300, height=OPTIM_GRAPH_HEIGHT, width=OPTIM_GRAPH_WIDTH, units="in", family="Arial")
plot
```

### PySOM - BC interp

```{r optim-pysom-bc-interp, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot_optim(data_optim_pysom_bc, "RPySOM-bc-interp")

plot <- box_plot_optim(box_plot_data)
ggsave(plot, device= cairo_pdf, path=".", filename=output_folder_path("optim-pysom-bc-int.pdf"), dpi=300, height=OPTIM_GRAPH_HEIGHT, width=OPTIM_GRAPH_WIDTH, units="in", family="Arial")
plot
```

### TruffleSOM - BC JIT

```{r optim-tsom-bc-jit, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot_optim(data_optim_tsom_bc, "TruffleSOM-graal-bc")

plot <- box_plot_optim(box_plot_data)
ggsave(plot, device= cairo_pdf, path=".", filename=output_folder_path("optim-tsom-bc-jit.pdf"), dpi=300, height=OPTIM_GRAPH_HEIGHT, width=OPTIM_GRAPH_WIDTH, units="in", family="Arial")
plot
```

### PySOM - BC JIT

```{r optim-pysom-bc-jit, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot_optim(data_optim_pysom_bc, "RPySOM-bc-jit")

plot <- box_plot_optim(box_plot_data)
ggsave(plot, device= cairo_pdf, path=".", filename=output_folder_path("optim-pysom-bc-jit.pdf"), dpi=300, height=OPTIM_GRAPH_HEIGHT, width=OPTIM_GRAPH_WIDTH, units="in", family="Arial")
plot
```

## Stats
```{r stats}
stats_tsom_ast_int <- compute_stats(data_optim_tsom_ast, "TruffleSOM-native-interp-ast")$stats
stats_tsom_bc_int <- compute_stats(data_optim_tsom_bc, "TruffleSOM-native-interp-bc")$stats
stats_tsom_ast_jit <- compute_stats(data_optim_tsom_ast, "TruffleSOM-graal")$stats
stats_tsom_bc_jit <- compute_stats(data_optim_tsom_bc, "TruffleSOM-graal-bc")$stats

stats_pysom_ast_int <- compute_stats(data_optim_pysom_ast, "RPySOM-ast-interp")$stats
stats_pysom_bc_int <- compute_stats(data_optim_pysom_bc, "RPySOM-bc-interp")$stats
stats_pyson_ast_jit <- compute_stats(data_optim_pysom_ast, "RPySOM-ast-jit")$stats
stats_pysom_bc_jit <- compute_stats(data_optim_pysom_bc, "RPySOM-bc-jit")$stats
```

## Write to text file

```{r write-file}
tex.file <- file("../../../paper/gen/individual-optimisations.tex")

# interpreter data for tsom
macros = c(
    Cmd("TSOMastInlineStructMedianX",
        X2((stats_tsom_ast_int |> filter(optim == "inlined control struc."))$median)),
    Cmd("TSOMastInlineStructMaxX",
        X2((stats_tsom_ast_int |> filter(optim == "inlined control struc."))$max)),
    Cmd("TSOMastInlineStructMinX",
        X2((stats_tsom_ast_int |> filter(optim == "inlined control struc."))$min)),
    
    Cmd("PySOMastInlineStructMedianX",
        X2((stats_pysom_ast_int |> filter(optim == "inlined control struc."))$median)),
    Cmd("PySOMastInlineStructMaxX",
        X2((stats_pysom_ast_int |> filter(optim == "inlined control struc."))$max)),
    Cmd("PySOMastInlineStructMinX",
        X2((stats_pysom_ast_int |> filter(optim == "inlined control struc."))$min)),
    
    Cmd("TSOMbcInlineStructMedianX",
        X2((stats_tsom_bc_int |> filter(optim == "inlined control struc."))$median)),
    Cmd("TSOMbcInlineStructMaxX",
        X2((stats_tsom_bc_int |> filter(optim == "inlined control struc."))$max)),
    Cmd("TSOMbcInlineStructMinX",
        X2((stats_tsom_bc_int |> filter(optim == "inlined control struc."))$min)),
    
    Cmd("PySOMbcInlineStructMedianX",
        X2((stats_pysom_bc_int |> filter(optim == "inlined control struc."))$median)),
    Cmd("PySOMbcInlineStructMaxX",
        X2((stats_pysom_bc_int |> filter(optim == "inlined control struc."))$max)),
    Cmd("PySOMbcInlineStructMinX",
        X2((stats_pysom_bc_int |> filter(optim == "inlined control struc."))$min)),
    
    Cmd("TSOMbcInlineStructMedian",
        X2((stats_tsom_bc_int |> filter(optim == "inlined control struc."))$median)),
    Cmd("TSOMbcInlineStructSlowest",
        X2((stats_tsom_bc_int |> filter(optim == "inlined control struc."))$max)),
    Cmd("TSOMastInlineCacheMedian",
        X2((stats_tsom_ast_int |> filter(optim == "inline caching"))$median)),
    Cmd("TSOMastInlineCacheSlowest",
        X2((stats_tsom_ast_int |> filter(optim == "inline caching"))$max)),
    Cmd("TSOMbcInlineCacheMedian",
        X2((stats_tsom_bc_int |> filter(optim == "inline caching"))$median)),
    Cmd("TSOMbcInlineCacheSlowest",
        X2((stats_tsom_bc_int |> filter(optim == "inline caching"))$max)),
    
    Cmd("TSOMbcInlineCacheMedianX",
        X2((stats_tsom_ast_int |> filter(optim == "inline caching"))$median)),
    Cmd("TSOMbcInlineCacheMaxX",
        X2((stats_tsom_ast_int |> filter(optim == "inline caching"))$max)),
    Cmd("TSOMbcInlineCacheMinX",
        X2((stats_tsom_ast_int |> filter(optim == "inline caching"))$min)),
    
    Cmd("PySOMastInlineCacheMedianX",
        X2((stats_pysom_ast_int |> filter(optim == "inline caching"))$median)),
    Cmd("PySOMastInlineCacheMaxX",
        X2((stats_pysom_ast_int |> filter(optim == "inline caching"))$max)),
    Cmd("PySOMastInlineCacheMinX",
        X2((stats_pysom_ast_int |> filter(optim == "inline caching"))$min))

  )

writeLines(macros, tex.file)
close(tex.file)
```
