# Max RSS

```{r load-scripts, echo=FALSE, include=FALSE}
# load libraries, the data, and prepare it
source("scripts/libraries.R", chdir=TRUE)
source("scripts/data-processing2.R")

output_folder <- "../../../paper/images/"

data_rss <- qread("../../../data/rss-data.qs")

# Unused.
get_comparison_table <- function(all_data, exe_bc_name, exe_ast_name, only_with_warmup=FALSE) {
  df_filtered <- all_data %>%
  filter(exe %in% c(exe_bc_name, exe_ast_name))

  df_new <- df_filtered %>%
   group_by(bench) %>%
    summarize(bc_value = mean(value[exe == exe_bc_name]),
             ast_value = mean(value[exe == exe_ast_name]))

  df_new
}

box_plot_rss <- function(data, colors = color_set_vms) {
  x_breaks <- c(0.5, 0.8, 1, 2, 3, 5, 10, 15, 30)
  
  breaks <- levels(droplevels(data)$exe)

  plot <- ggplot(data, aes(x=ratio, y=reorder(exe, -ratio, FUN = median)))
  plot <- plot + 
    geom_vline(aes(xintercept=1),    colour="#999999", linetype="solid") +
    geom_vline(aes(xintercept=2), colour="#999999", linetype="dotted") +
    geom_vline(aes(xintercept=10), colour="#999999", linetype="dotted")
  plot <- plot + geom_boxplot(outlier.size = 0.9,
                              outlier.alpha = 0.6,
                              width=0.5,
                              outlier.shape = 22,
                              aes(colour = exe, fill = exe), 
                              alpha=0.4) +
    scale_x_log10(breaks = x_breaks) +
    scale_y_discrete(label = function (x) parse(text=x)) +
    scale_color_manual(values = colors) +
    scale_fill_manual(values = colors) +
    theme_simple() +
    theme(
      axis.text.x = element_text(angle= 90, vjust=0.5, hjust=1),
      axis.title.x = theme_simple_axis_title(),
      legend.position="none") +
    #scale_y_log10(breaks=c(1,2,3,10,20,30,50,100,200,300,500,1000)) + #limit=c(0,30), breaks=seq(0,100,5), expand = c(0,0)
    ylab("") +
    xlab("")
  
  plot
} 

as_human_mem <- function(x, digits = 3) {
  if (length(x) > 1) {
    return(sapply(x, as_human_mem))
  }
  
  if (is.na(x) || length(x) == 0) {
    return("")
  }
  

  m <- x * 1000
  mem <- c(" b", " kb", " MB", " GB")
  i <- 1
  while (i <= 3 && m >= 1000) {
    m <- m / 1000
    i <- i + 1
  }
  paste0(format(m, digits = digits), mem[[i]])
}


box_plot_in_kb <- function(data, colors = color_set_vms, parse_y_labels = FALSE) {
#  x_breaks <- c(0.5, 0.8, 1, 2, 3, 5, 10, 15, 30)
  
  breaks <- levels(droplevels(data)$exe)

  plot <- ggplot(data, aes(x=value, y=reorder(exe, -ratio, FUN = median)))
  plot <- plot + geom_boxplot(outlier.size = 0.9,
                              outlier.alpha = 0.6,
                              width=0.5,
                              outlier.shape = 22,
                              aes(colour = exe, fill = exe), 
                              alpha=0.4) +
    scale_x_log10(labels = as_human_mem) +
    scale_color_manual(values = colors) +
    scale_fill_manual(values = colors) +
    theme_simple() +
    theme(
      axis.text.x = element_text(angle= 90, vjust=0.5, hjust=1),
      axis.title.x = theme_simple_axis_title(),
      legend.position="none") +
    #scale_y_log10(breaks=c(1,2,3,10,20,30,50,100,200,300,500,1000)) + #limit=c(0,30), breaks=seq(0,100,5), expand = c(0,0)
    ylab("") +
    xlab("")
  
  if (parse_y_labels) {
    plot <- plot +
      scale_y_discrete(label = function (x) parse(text=x))
  }
  
  plot
}

get_data_for_box_plot <- function(all_data, baseline_name, exe_names) {
  # For easy explortion of function in RStudio:
  # all_data <- data_rss
  # baseline_name <- "RPySOM-bc-interp"
  # exe_names <- c("RPySOM-bc-interp", "RPySOM-ast-interp")
  
  df <- all_data |> filter(exe %in% exe_names)

  df_baseline <- df |>
    filter(exe == baseline_name) |>
    select(-c(exe, unit)) |>
    group_by(bench) |>
    summarise(base = median(value))
  
  df2 <- df |>
    left_join(
      df_baseline,
      by = c("bench")) |>
    mutate(ratio = value / base)
  
  # try renaming TODO: get rid of one of them after unifying the experiment names
  suppressMessages(df2$exe <- revalue(df2$exe, unify_overview_memory_data) %>% droplevels())
  suppressMessages(df2$exe <- revalue(df2$exe, vm_names) %>% droplevels())
  df2
}

#data_repr_tsom_old <- load_data_url("https://rebench.stefan-marr.de/TruffleSOM/data/2622") %>% 
#    filter(criterion == "Allocated") %>%
#    group_by(expid, runid, trialid, bench, exe, cmdline, extraargs, invocation) %>%
#    summarize(iteration = 1, value = sum(value))

data_repr_tsom <- load_data_url("https://rebench.stefan-marr.de/TruffleSOM/data/2838") %>% 
    filter(criterion == "Allocated") |>
    mutate(ratio = 1) # bad code to make it work with the previous boxplot function...

data_repr_pysom <- load_data_url("https://rebench.stefan-marr.de/RPySOM/data/2860")
data_repr_pysom <- distinct(data_repr_pysom, exe, runid, cmdline, cores, extraargs, envid, .keep_all = TRUE)
```

## BCvsAST - interpreter only

```{r rss-interp, fig.width=8, fig.height=2.2, echo=FALSE}
#box_plot_data <- get_data_for_box_plot_rss(data_rss, 
#                                           "TruffleSOM-native-interp-bc",
#                                           c("TruffleSOM-native-interp-bc", "TruffleSOM-native-interp-ast"))

#box_plot_data <- get_data_for_box_plot_rss(data_rss, 
#                                           "RPySOM-bc-interp",
#                                           c("RPySOM-bc-interp", "RPySOM-ast-interp"))

box_plot_data <- get_data_for_box_plot(data_rss,
                                           "RPySOM-bc-interp",
                                           c("RPySOM-bc-interp", "RPySOM-ast-interp",
                                             "TruffleSOM-native-interp-bc", "TruffleSOM-native-interp-ast"))


#print(kable(df2), type="latex", comment=FALSE)
plot <- box_plot_rss(box_plot_data)
#ggsave("rss-interp.pdf", plot, dpi = 300, height = 200, width = 400, units="mm", device="pdf")
#ggsave(plot, device= cairo_pdf, path=".", filename=paste0(output_folder, "/rss-interp.pdf"), dpi=300, height=50, width=100, units="mm", family="Arial")

plot
```


## BCvsAST - JIT

```{r rss-jit, fig.width=8, fig.height=2.2, echo=FALSE}
#box_plot_data2 <- get_data_for_box_plot_rss(data_rss,
#                                      "RPySOM-bc-jit",
#                                       c("RPySOM-bc-jit", "RPySOM-ast-jit"))

box_plot_data <- get_data_for_box_plot(data_rss,
                                           "RPySOM-bc-jit",
                                           c("RPySOM-bc-jit", "RPySOM-ast-jit", "TruffleSOM-graal", "TruffleSOM-graal-bc"))


#print(kable(df2), type="latex", comment=FALSE)
plot <- box_plot_rss(box_plot_data)
#ggsave(plot, device= cairo_pdf, path=".", filename=paste0(output_folder, "rss-jit.pdf"), dpi=300, height=50, width=100, units="mm", family="Arial")
#ggsave(plot, device= cairo_pdf, path=".", filename="rss-jit.pdf", dpi=300, height=4, width=8.5, units="in", family="Arial")

plot
```

## BCvsAST - PySOM int

```{r rss-pysom-int, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot(data_rss,
                                           "RPySOM-bc-interp",
                                           c("RPySOM-bc-interp", "RPySOM-ast-interp"))

plot <- box_plot_in_kb(box_plot_data, parse_y_labels = TRUE)
#ggsave(plot, device= cairo_pdf, path=".", filename=paste0(output_folder, "/rss-interp-pysom.pdf"), dpi=300, height=1.3, width=2.6, units="in", family="Arial")

plot
```

## BCvsAST - TruffleSOM int

```{r rss-tsom-int, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot(data_rss,
                                           "TruffleSOM-native-interp-bc",
                                           c("TruffleSOM-native-interp-bc", "TruffleSOM-native-interp-ast"))

plot <- box_plot_in_kb(box_plot_data, parse_y_labels = TRUE)
#ggsave(plot, device= cairo_pdf, path=".", filename=paste0(output_folder, "/rss-interp-tsom.pdf"), dpi=300, height=1.3, width=2.6, units="in", family="Arial")

plot
```

## BCvsAST - PySOM JIT

```{r rss-pysom-jit, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot(data_rss,
                                           "RPySOM-bc-jit",
                                           c("RPySOM-bc-jit", "RPySOM-ast-jit"))

plot <- box_plot_in_kb(box_plot_data, parse_y_labels = TRUE)
#ggsave(plot, device= cairo_pdf, path=".", filename=paste0(output_folder, "/rss-jit-pysom.pdf"), dpi=300, height=1.3, width=2.6, units="in", family="Arial")

plot
```

## BCvsAST - TruffleSOM JIT

```{r rss-tsom-jit, fig.width=8, fig.height=2.2, echo=FALSE}
box_plot_data <- get_data_for_box_plot(data_rss,
                                           "TruffleSOM-graal-bc",
                                           c("TruffleSOM-graal", "TruffleSOM-graal-bc"))

plot <- box_plot_in_kb(box_plot_data, parse_y_labels = TRUE)
#ggsave(plot, device= cairo_pdf, path=".", filename=paste0(output_folder, "/rss-jit-tsom.pdf"), dpi=300, height=1.3, width=2.6, units="in", family="Arial")

plot
```
