---
title: "Section 5.5.2 Memory Usage for Program Representation"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
source("scripts/libraries.R", chdir=TRUE)
source("scripts/data-processing2.R")

#raw_data <- rbind(
#  load_rebench_data_file("../../../paper/data/max-rss-test-testgc-tsom.002.data.bz2"),
#  load_rebench_data_file("../../../paper/data/max-rss-test-testgc.003.data.bz2") |>
#    filter(str_detect(exe, "RPySOM-bc-interp", negate=TRUE)),
#  load_rebench_data_file("../../../paper/data/max-rss-test-testgc-fix-pysom.data.bz2"))

# will need some formatting
data <- load_rebench_data_file("../../../benchmark.data")

raw_data <- factorize_result(raw_data)

data <- raw_data |>
  select(!c(suite, cores, extraargs, varvalue, machine)) |>
  filter(criterion == "MaxRSS") |>
  droplevels()

data$exe <- revalue(data$exe,
                    c("RPySOM-bc-interp"="PySOM BC",
                      "RPySOM-ast-interp"="PySOM AST",
                      "TruffleSOM-native-interp-ast" = "TrSOM AST",
                      "TruffleSOM-native-interp-bc" = "TrSOM BC"))

data <- data |>
  mutate(exe.bench = paste(exe, bench))
data$exe.bench <- factor(data$exe.bench)

med <- data |>
  group_by(bench, exe, inputsize, criterion, unit, exe.bench) |>
  summarise(median = median(value),
            .groups = "drop")
```



```{r maxrss-increase, include=FALSE, echo=FALSE}
# ggplot(med, aes(x=inputsize, y=median, group=exe.bench, color=exe.bench)) + geom_line()
```

#### Increase of MaxRSS for Each Copy of the SOM Unit Tests

This plot is not included in the paper, but shows that MaxRSS approximates well
the memory use of the program representation, since it is increasing with the
number of program copies.

```{r per-iter-increase, echo=FALSE}
med_diff <- med |>
  group_by(bench, exe, criterion, unit, exe.bench) |>
  mutate(diff = median - lag(median)) |>
  na.omit()
ggplot(med_diff, aes(x=inputsize, y=diff, group=exe.bench, color=exe.bench)) + geom_line()
```

#### Sec. 5.5.2 Numbers Used

```{r stats, echo=FALSE}
stats <- med_diff |>
  group_by(bench, exe, criterion, unit, exe.bench) |>
  summarise(median.diff = median(diff),
            .groups = "drop") |>
  mutate(is.pysom = str_detect(exe, "PySOM"))

base <- stats |>
  filter(str_detect(exe, "BC")) |>
  mutate(base = median.diff) |>
  select(!c(exe.bench, median.diff, exe))

norm <- stats |>
  left_join(base, by = c("bench", "criterion", "unit", "is.pysom")) |>
  mutate(ratio = median.diff / base)

id <- function(x) { x }

tabular(bench*exe ~ (median.diff + ratio) * id, data=norm)
```
#### Lines of Code Statistics

```{r code-stats, echo=FALSE}
code_stats <- read.csv("../../../paper/data/program-rep.cloc.csv")
code_stats$language <- factor(code_stats$language)
tabular(
  language ~ (files + blank + comment + code) * id,
  data=code_stats)
```
