---
title: "Section 5.4 Warmup Behavior"
output: html_document
---


```{r prepare-data, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, dev='svg'}
# load libraries, the data, and prepare it
source("scripts/libraries.R", chdir=TRUE)

data <- load_rebench_data_file("../../../benchmark.data")
data <- subset(data, criterion == "total" & suite != "progr-rep-mem")

data$exe <- ifelse(data$exe == "TruffleSOM-ast-NativeCE-int", "TruffleSOM-native-ast", data$exe)
data$exe <- ifelse(data$exe == "TruffleSOM-bc-NativeCE-int", "TruffleSOM-native-bc", data$exe)

data <- subset(data, exe %in% c(
  "TruffleSOM-native-ast", "TruffleSOM-native-bc",
  "PySOM-ast-jit", "PySOM-bc-jit")) |>
  factorize_result()

MAX_ITER <- 100

all_data <- data

filtered <- all_data |> select_data(iteration <= MAX_ITER)

base <- filtered |>
  compute_baseline("TruffleSOM-native-ast")

norm <- filtered |>
          left_join(base, by = c("bench")) |>
          group_by(bench) |>
          transform(ratio_median = value / base_median)

get_warmup_plots <- function(data, baseline_name, y_lab, dont_rename = FALSE) {
  # data <- native_image_data
  # baseline_name <- "TruffleSOM-native-ast"
  # y_lab <- expression(Normalized~to~median(TSOM[AST]))
  # dont_rename <- FALSE
  filtered <- data |> select_data(iteration <= MAX_ITER)
  
  base <- filtered |>
    compute_baseline(baseline_name)
  
  norm <- filtered |>
            left_join(base, by = c("bench")) |>
            group_by(bench) |>
            transform(ratio_median = value / base_median)

  if (!dont_rename) {
    suppressMessages(norm$exe <- revalue(norm$exe, vm_names))
  }
  
  vms <- levels(droplevels(norm)$exe)
  
  plots <- ggplot(norm, aes(x=iteration, y=ratio_median)) +
    geom_line(aes(colour = exe), linewidth=0.3)+
    scale_y_log10() +
    scale_color_manual(values = color_set_vms, label = function (x) parse(text=x), col) +
    theme_simple() +
    theme(
      legend.title = element_blank(),
      legend.text.align = 0,
      legend.position = c(0.9, 0.525)) +
    ylab(y_lab) +
    facet_wrap(~ bench, scales = "free_y")
  
  plots
}
```

#### Sec. 5.4 Figure 4 TSOM Interpreter on GraalVM Native Image

```{r warmup-plot, echo=FALSE, dev='png', fig.keep='all', fig.width=10, fig.height=6}
native_image_data <- all_data |> filter(exe %in% c("TruffleSOM-native-ast", "TruffleSOM-native-bc"))
plot_native <- get_warmup_plots(native_image_data, "TruffleSOM-native-ast", expression(Normalized~to~median(TSOM[AST])))

print(plot_native)
```

#### Sec. 5.4 Figure 5 PySOM Interpreter

```{r warmup-plot-pysom, echo=FALSE, dev='png', fig.keep='all', fig.width=10, fig.height=6}
pysom_data <- all_data |> filter(exe %in% c("PySOM-ast-jit", "PySOM-bc-jit"))
plot_pysom <- get_warmup_plots(pysom_data, "PySOM-ast-jit", expression(Normalized~to~median(PySOM[AST]))) # "Java-C2-jit")
print(plot_pysom)

OUTPUT_WIDTH <- 5.5
OUTPUT_HEIGHT <- 3.3
output_folder <- "../../../paper/images/"
```
