---
title: "Stefan: Looking at MaxRSS for Test1-100 and TestGC1-100"
output: html_document
date: "2023-04-07"
---

```{r setup, include=FALSE, echo=FALSE}
if (Sys.getenv("USER") == "smarr") { setwd("/Users/smarr/Projects/ast-vs-bc-interp/are-we-fast-yet/report/bc-vs-ast") } else { setwd("/home/octavel/PhD/papers/ast-vs-bc-interp/are-we-fast-yet/report/bc-vs-ast") }
source("scripts/libraries.R", chdir=TRUE)
source("scripts/data-processing2.R")

raw_data <- rbind(
  load_rebench_data_file("../../../paper/data/max-rss-test-testgc-tsom.002.data.bz2"),
  load_rebench_data_file("../../../paper/data/max-rss-test-testgc.003.data.bz2") |>
    filter(str_detect(exe, "RPySOM-bc-interp", negate=TRUE)),
  load_rebench_data_file("../../../paper/data/max-rss-test-testgc-fix-pysom.data.bz2"))

raw_data <- factorize_result(raw_data)

data <- raw_data |>
  select(!c(suite, cores, extraargs, varvalue, machine)) |>
  filter(criterion == "MaxRSS") |>
  droplevels()

data$exe <- revalue(data$exe,
                    c("RPySOM-bc-interp"="PySOM BC",
                      "RPySOM-ast-interp"="PySOM AST",
                      "TruffleSOM-native-interp-ast" = "TrSOM AST",
                      "TruffleSOM-native-interp-bc" = "TrSOM BC"))

data <- data |>
  mutate(exe.bench = paste(exe, bench))
data$exe.bench <- factor(data$exe.bench)

med <- data |>
  group_by(bench, exe, inputsize, criterion, unit, exe.bench) |>
  summarise(median = median(value),
            .groups = "drop")
```

## MaxRSS Increase


```{r maxrss-increase}
ggplot(med, aes(x=inputsize, y=median, group=exe.bench, color=exe.bench)) + geom_line()
```

## Per Iteration Increase

```{r per-iter-increase}
med_diff <- med |>
  group_by(bench, exe, criterion, unit, exe.bench) |>
  mutate(diff = median - lag(median)) |>
  na.omit()
ggplot(med_diff, aes(x=inputsize, y=diff, group=exe.bench, color=exe.bench)) + geom_line()
```

## Stats

```{r stats}
stats <- med_diff |>
  group_by(bench, exe, criterion, unit, exe.bench) |>
  summarise(median.diff = median(diff),
            .groups = "drop") |>
  mutate(is.pysom = str_detect(exe, "PySOM"))

base <- stats |>
  filter(str_detect(exe, "BC")) |>
  mutate(base = median.diff) |>
  select(!c(exe.bench, median.diff, exe))

norm <- stats |>
  left_join(base, by = c("bench", "criterion", "unit", "is.pysom")) |>
  mutate(ratio = median.diff / base)

id <- function(x) { x }

tabular(bench*exe ~ (median.diff + ratio) * id, data=norm)
```
## Code Stats

```{r code-stats}
code_stats <- read.csv("../../../paper/data/program-rep.cloc.csv")
code_stats$language <- factor(code_stats$language)
tabular(
  language ~ (files + blank + comment + code) * id,
  data=code_stats)
```


## Write to text file

```{r write-file}
X2 <- function(num) {
  format(num, digits=2, nsmall = 2)
}

WithT <- function(num) {
  format(num, big.mark = ",")
}

tex.file <- file("../../../paper/gen/program-rep.tex")

macros = c(
  paste0("\\newcommand{\\progRepAstOverheadPySomWOExec}{",
         X2((norm |> filter(exe == "PySOM AST", bench == "TestGC"))$ratio), "\\xspace}"),
  paste0("\\newcommand{\\progRepAstOverheadPySomWithExec}{",
         X2((norm |> filter(exe == "PySOM AST", bench == "Test"))$ratio), "\\xspace}"),
  paste0("\\newcommand{\\progRepAstOverheadTrSomWOExec}{",
         X2((norm |> filter(exe == "TrSOM AST", bench == "TestGC"))$ratio), "\\xspace}"),
  paste0("\\newcommand{\\progRepAstOverheadTrSomWithExec}{",
         X2((norm |> filter(exe == "TrSOM AST", bench == "Test"))$ratio), "\\xspace}"),
  
  paste0("\\newcommand{\\progRepNumFiles}{",
         WithT((code_stats |> filter(language == "Smalltalk"))$files),
         "\\xspace}"),
  paste0("\\newcommand{\\progRepNumLOC}{",
         WithT((code_stats |> filter(language == "Smalltalk"))$code),
         "\\xspace}")
)

writeLines(macros, tex.file)
close(tex.file)
```


