## This file defines common functions used for data processing.

load_data_file <- function (file, row_names) {
  if (missing(row_names)) {
    # these row names are hard coded and might not be applicable
    # names like this are generated by ReBench
    row_names <- c("TimeStamp", "Value", "Unit", "Criterion", "Benchmark",
                   "VM", "Suite", "Extra", "Warmup", "Cores", "InputSize",
                   "Var")
  }
  
  bench <- rbind(read.table(file, sep="\t", header=FALSE, col.names=row_names,
                            fill=TRUE))
  bench
}

prepare_vm_names <- function(data) {
  # Reorder
  data$VM <- factor(data$VM, c("Java", "PyPy", "RPySOM-jit",
                               "TruffleSOM-graal", "TruffleSOM-graal-no-split",
                               "SOMpp"))
  
  name_map <-     list("Java"                  = "Java",
                       "PyPy"                  = "PyPy",
                       "RPySOM-jit"            = "RPySOM",
                       
                       "TruffleSOM-graal"      = "TruffleSOM",
                       "TruffleSOM-graal-no-split" = "TruffleSOM.ns",
                       "SOMpp"                 = "SOM++")
  # Rename
  levels(data$VM)  <- map_names(
    levels(data$VM),
    name_map)
  data
}

map_names <- function(old_names, name_map) {
  for (i in 1:length(old_names)) {
    old_name <- old_names[[i]]
    if (!is.null(name_map[[old_name]])) {
      old_names[i] <- name_map[[old_name]]
    }
  }
  old_names
}
