## This file defines common functions used for data processing.

load_data_file <- function (file, row_names) {
  if (missing(row_names)) {
    # these row names are hard coded and might not be applicable
    # names like this are generated by ReBench
    row_names <- c("TimeStamp", "Value", "Unit", "Criterion", "Benchmark",
                   "VM", "Suite", "Extra", "Warmup", "Cores", "InputSize",
                   "Var")
  }
  
  bench <- rbind(read.table(file, sep="\t", header=FALSE, col.names=row_names,
                            fill=TRUE))
  bench
}
